version: 2
updates:
  - package-ecosystem: "uv"
    directories:
      - "**/*"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directories:
      - "**/packages/**"
      - "**/tools/**"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directories:
      - "**/*"
    schedule:
      interval: "weekly"
