version: 2
updates:
  - package-ecosystem: "uv"
    directories:
      - "**/*"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directories:
      - "**/*"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directories:
      - "**/*"
    schedule:
      interval: "weekly"
