from __future__ import annotations
INTEGRATION_NAME = "CaseFederation"

PING_SCRIPT_NAME = "Ping"
FEDERATION_SYNC_JOB_SCRIPT_NAME = "SyncJob"

FEDERATION_BASE_ENDPOINT_TEMPLATE: str = "{api_root}/external/v1/federation/cases"
FEDERATION_SYNC_ENDPOINT_TEMPLATE = FEDERATION_BASE_ENDPOINT_TEMPLATE + "/batch-patch"
FEDERATION_FETCH_ENDPOINT_TEMPLATE = FEDERATION_BASE_ENDPOINT_TEMPLATE

SUCCESS_STATUS_CODE = 200
