# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    ".idea",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

line-length = 120
indent-width = 4

target-version = "py311"

[lint]
select = ["ALL"]

ignore = [
    "COM812",
    "D203",
    "D213",
    "D100",
    "D101",
    "D104",
    "D105",
    "D107",
    "TID252",
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

preview = true

[lint.per-file-ignores]
"**/[Tt]ests/**" = [
    "S101",
    "ARG",
    "FBT",
    "PLR2004",
    "S311",
    "D",
    "DOC",
    "PLR6301",
    "PLC1901",
    "RUF069",
    "TID252",
]

# Specific Integrations
"active_directory/**" = ["ALL"]
"alexa/**" = ["ALL"]
"algo_sec/**" = ["ALL"]
"alien_vault_anywhere/**" = ["ALL"]
"alien_vault_appliance/**" = ["ALL"]
"alien_vault_ti/**" = ["ALL"]
"amazon_macie/**" = ["ALL"]
"anomali/**" = ["ALL"]
"anomali_staxx/**" = ["ALL"]
"anomali_threat_stream/**" = ["ALL"]
"any_run/**" = ["ALL"]
"api_void/**" = ["ALL"]
"app_sheet/**" = ["ALL"]
"arc_sight_logger/**" = ["ALL"]
"arcsight/**" = ["ALL"]
"area1/**" = ["ALL"]
"armis/**" = ["ALL"]
"attivo/**" = ["ALL"]
"auto_focus/**" = ["ALL"]
"aws_cloud_trail/**" = ["ALL"]
"aws_cloud_watch/**" = ["ALL"]
"aws_guard_duty/**" = ["ALL"]
"aws_security_hub/**" = ["ALL"]
"awsec2/**" = ["ALL"]
"awsiam_access_analyzer/**" = ["ALL"]
"awss3/**" = ["ALL"]
"awswaf/**" = ["ALL"]
"axonius/**" = ["ALL"]
"azure_security_center/**" = ["ALL"]
"blue_liv/**" = ["ALL"]
"bmc_helix_remedy_force/**" = ["ALL"]
"bmc_remedy_itsm/**" = ["ALL"]
"bulk_who_is/**" = ["ALL"]
"ca_service_desk/**" = ["ALL"]
"case_federation/**" = ["ALL"]
"cb_defense/**" = ["ALL"]
"cb_enterprise_edr/**" = ["ALL"]
"cb_live_response/**" = ["ALL"]
"cb_response/**" = ["ALL"]
"certly/**" = ["ALL"]
"check_point_cloud_guard/**" = ["ALL"]
"check_point_firewall/**" = ["ALL"]
"check_point_sand_blast/**" = ["ALL"]
"check_point_threat_reputation/**" = ["ALL"]
"cisco_amp/**" = ["ALL"]
"cisco_firepower_management_center/**" = ["ALL"]
"cisco_ise/**" = ["ALL"]
"cisco_threat_grid/**" = ["ALL"]
"cloudflare/**" = ["ALL"]
"cofense_triage/**" = ["ALL"]
"cuckoo/**" = ["ALL"]
"cyber_ark_pam/**" = ["ALL"]
"cyber_ark_vault/**" = ["ALL"]
"cybereason/**" = ["ALL"]
"cyberint/**" = ["ALL"]
"cylance/**" = ["ALL"]
"cynet/**" = ["ALL"]
"d_shield/**" = ["ALL"]
"deep_sight/**" = ["ALL"]
"devo/**" = ["ALL"]
"digital_shadows/**" = ["ALL"]
"easy_vista/**" = ["ALL"]
"elastic_search_v7/**" = ["ALL"]
"elastica_cloud_soc/**" = ["ALL"]
"endgame/**" = ["ALL"]
"exabeam_advanced_analytics/**" = ["ALL"]
"exchange_extension_pack/**" = ["ALL"]
"f5_bigi_pi_control_api/**" = ["ALL"]
"f5_bigip_access_policy_manager/**" = ["ALL"]
"falcon_sandbox/**" = ["ALL"]
"file_operation/**" = ["ALL"]
"fire_eye_ax/**" = ["ALL"]
"fire_eye_cm/**" = ["ALL"]
"fire_eye_etp/**" = ["ALL"]
"fire_eye_helix/**" = ["ALL"]
"fire_eye_hx/**" = ["ALL"]
"fire_eye_nx/**" = ["ALL"]
"fore_scout_counter_act/**" = ["ALL"]
"forti_manager/**" = ["ALL"]
"fortigate/**" = ["ALL"]
"fortinet_forti_siem/**" = ["ALL"]
"freshworks_freshservice/**" = ["ALL"]
"google_alert_center/**" = ["ALL"]
"google_chat/**" = ["ALL"]
"google_cloud_storage/**" = ["ALL"]
"google_grr/**" = ["ALL"]
"google_translate/**" = ["ALL"]
"harmony_mobile/**" = ["ALL"]
"http/**" = ["ALL"]
"humio/**" = ["ALL"]
"i_boss/**" = ["ALL"]
"internet_storm_center/**" = ["ALL"]
"intsights/**" = ["ALL"]
"iron_port/**" = ["ALL"]
"iron_scales/**" = ["ALL"]
"ivanti_endpoint_manager/**" = ["ALL"]
"joe_sandbox/**" = ["ALL"]
"log_point/**" = ["ALL"]
"log_rhythm/**" = ["ALL"]
"mal_share/**" = ["ALL"]
"malware_domain_list/**" = ["ALL"]
"mandiant_asm/**" = ["ALL"]
"mc_afee_epo/**" = ["ALL"]
"mc_afee_esm/**" = ["ALL"]
"mc_afee_mvision_edr/**" = ["ALL"]
"mc_afee_mvision_edrv2/**" = ["ALL"]
"mc_afee_mvision_epo/**" = ["ALL"]
"mc_afee_tiedxl/**" = ["ALL"]
"mc_afee_web_gateway/**" = ["ALL"]
"misp/**" = ["ALL"]
"mitre_attck/**" = ["ALL"]
"mongo_db/**" = ["ALL"]
"mssql/**" = ["ALL"]
"nessus_scanner/**" = ["ALL"]
"netskope/**" = ["ALL"]
"nozomi_networks/**" = ["ALL"]
"office365_cloud_app_security/**" = ["ALL"]
"office365_management_api/**" = ["ALL"]
"opswat_metadefender/**" = ["ALL"]
"palo_alto_ngfw/**" = ["ALL"]
"palo_alto_panorama/**" = ["ALL"]
"passive_total/**" = ["ALL"]
"phishing_initiative/**" = ["ALL"]
"postgre_sql/**" = ["ALL"]
"proof_point_ps/**" = ["ALL"]
"qualys_edr/**" = ["ALL"]
"qualys_vm/**" = ["ALL"]
"rapid7_insight_idr/**" = ["ALL"]
"rapid7_insight_vm/**" = ["ALL"]
"recorded_future/**" = ["ALL"]
"redis/**" = ["ALL"]
"remote_agent_utilities/**" = ["ALL"]
"reversinglabs_titanium/**" = ["ALL"]
"rsa_archer/**" = ["ALL"]
"rsa_net_witness/**" = ["ALL"]
"rsa_net_witness_platform/**" = ["ALL"]
"runners/**" = ["ALL"]
"salesforce/**" = ["ALL"]
"sccm/**" = ["ALL"]
"sentinel_one/**" = ["ALL"]
"sep/**" = ["ALL"]
"sep12/**" = ["ALL"]
"service_desk_plus/**" = ["ALL"]
"service_desk_plus_v3/**" = ["ALL"]
"service_now/**" = ["ALL"]
"shodan/**" = ["ALL"]
"siemplify_threat_fuse/**" = ["ALL"]
"slack/**" = ["ALL"]
"snowflake/**" = ["ALL"]
"solar_winds_orion/**" = ["ALL"]
"sonic_wall_beta/**" = ["ALL"]
"sophos/**" = ["ALL"]
"ssh/**" = ["ALL"]
"ssl_labs/**" = ["ALL"]
"stealthwatch/**" = ["ALL"]
"sumo_logic_cloud_siem/**" = ["ALL"]
"sumologic/**" = ["ALL"]
"symantec_atp/**" = ["ALL"]
"symantec_blue_coat_proxy_sg/**" = ["ALL"]
"symantec_email_security_cloud/**" = ["ALL"]
"sys_aid/**" = ["ALL"]
"talos/**" = ["ALL"]
"tenable_security_center/**" = ["ALL"]
"threat_crowd/**" = ["ALL"]
"threat_exchange/**" = ["ALL"]
"tor/**" = ["ALL"]
"trend_micro_apex_central/**" = ["ALL"]
"trend_micro_cloud_app_security/**" = ["ALL"]
"trend_micro_deep_security/**" = ["ALL"]
"trend_vision_one/**" = ["ALL"]
"tru_star/**" = ["ALL"]
"unshorten_me/**" = ["ALL"]
"url_void/**" = ["ALL"]
"v_sphere/**" = ["ALL"]
"varonis_data_security_platform/**" = ["ALL"]
"vectra/**" = ["ALL"]
"virus_total/**" = ["ALL"]
"vm_ray/**" = ["ALL"]
"x_force/**" = ["ALL"]
"zendesk/**" = ["ALL"]
"cisco_orbital/**" = ["ALL"]
"cyber_x/**" = ["ALL"]
"fire_eye_ex/**" = ["ALL"]
"f5_big_iq/**" = ["ALL"]
"hcl_big_fix_inventory/**" = ["ALL"]
"illusive_networks/**" = ["ALL"]
"juniper_vsrx/**" = ["ALL"]
"lastline/**" = ["ALL"]
"mc_afee_active_response/**" = ["ALL"]
"mc_afee_atd/**" = ["ALL"]
"mc_afee_nsm/**" = ["ALL"]
"micro_focus_itsma/**" = ["ALL"]
"mobile_iron/**" = ["ALL"]
"observe_it/**" = ["ALL"]
"outpost24/**" = ["ALL"]
"portnox/**" = ["ALL"]
"reversinglabs_a1000/**" = ["ALL"]
"stealthwatch_v610/**" = ["ALL"]
"symantec_content_analysis/**" = ["ALL"]
"symantec_icdx/**" = ["ALL"]
"site24x7/**" = ["ALL"]
"splash/**" = ["ALL"]
"websense/**" = ["ALL"]

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks, and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = true

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"

preview = true
