name: Execute Playbook
description: Initiate a playbook execution in Cofense Triage.
integration_identifier: CofenseTriage
parameters:
-   name: Report ID
    default_value: ''
    type: string
    description: Specify the ID of the report on which you want to execute the playbook.
    is_mandatory: true
-   name: Playbook Name
    default_value: ''
    type: string
    description: Specify the name of the playbook that needs to be executed.
    is_mandatory: true
dynamic_results_metadata: []
creator: admin
