[project]
name = "google_cloud_api"
version = "11.0"
description = "Google Cloud API integration was designed for you to execute Google Cloud API without the need of writing any code."
requires-python = ">=3.11,<3.12"
dependencies = [ "environmentcommon", "google-api-core==2.19.2", "google-auth>=2.34.0", "googleapis-common-protos==1.65.0", "pyzipper==0.3.6", "requests>=2.32.4", "tipcommon",]

[dependency-groups]
dev = [ "integration-testing", "pytest>=9.1.1", "pytest-json-report>=1.5.0", "soar-sdk", "beautifulsoup4>=4.12.3", "lxml>=5.3.0",]

[tool.uv]
[[tool.uv.index]]
url = "https://pypi.org/simple"
default = true

[tool.uv.sources.environmentcommon]
path = "../../../../packages/envcommon/whls/EnvironmentCommon-1.0.2-py2.py3-none-any.whl"

[tool.uv.sources.tipcommon]
path = "../../../../packages/tipcommon/whls/TIPCommon-2.2.6-py2.py3-none-any.whl"

[tool.uv.sources.soar-sdk]
git = "https://github.com/chronicle/soar-sdk.git"

[tool.uv.sources.integration-testing]
path = "../../../../packages/integration_testing_whls/integration_testing-2.2.6-py3-none-any.whl"
