name: Search Environment Custom Lists
description: Search a specified string within the records of an environment's 
  custom list. (If no values are provided will return all custom lists records)
integration_identifier: Lists
parameters:
- name: String to Search
  default_value: ''
  type: string
  description: String to search within list values
  is_mandatory: false
- name: Categories
  default_value: ''
  type: string
  description: Comma separated values
  is_mandatory: false
dynamic_results_metadata:
- result_name: JsonResult
  show_result: true
  result_example_path: 
    resources/SearchEnvironmentCustomLists_JsonResult_example.json
default_result_value: ''
creator: 464c66fb-e0db-48d9-8c72-d2a408bb425d
script_result_name: Match_Records
