name: Get Mailbox Account Out Of Facility Settings
description: Use the Get Mailbox Account Out Of Facility Settings action to retrieve
    the mailbox account out of facility (OOF) settings for the Google SecOps User
    entity provided. The Get Mailbox Account Out Of Facility Settings action uses
    the beta version of Microsoft Graph API. This action runs on the Google SecOps
    User entity.
documentation_link: https://cloud.google.com/chronicle/docs/soar/marketplace-integrations/microsoft-graph-mail-delegated#get_mailbox_account_out_of_facility_settings
integration_identifier: MicrosoftGraphMailDelegated
parameters: []
dynamic_results_metadata:
-   result_example_path: resources/get_mailbox_account_out_of_facility_settings_JsonResult_example.json
    result_name: JsonResult
    show_result: true
creator: Admin
