from __future__ import annotations
INTEGRATION_NAME = "PaloAltoNGFW"

PING_SCRIPT_NAME = f"{INTEGRATION_NAME} - Ping"
ADD_IPS_TO_GROUP_SCRIPT_NAME = f"{INTEGRATION_NAME} - AddIpsToGroup"
BLOCK_IPS_IN_POLICY_SCRIPT_NAME = f"{INTEGRATION_NAME} - BlockIpsInPolicy"
BLOCK_URLS_SCRIPT_NAME = f"{INTEGRATION_NAME} - BlockURLs"
COMMIT_CHANGES_SCRIPT_NAME = f"{INTEGRATION_NAME} - CommitChanges"
EDIT_BLOCKED_APPLICATIONS_SCRIPT_NAME = f"{INTEGRATION_NAME} - EditBlockedApplications"
GET_BLOCKED_APPLICATIONS_SCRIPT_NAME = f"{INTEGRATION_NAME} - GetBlockedApplications"
REMOVE_IP_FROM_GROUP_SCRIPT_NAME = f"{INTEGRATION_NAME} - RemoveIpFromGroup"
UNBLOCK_IPS_IN_POLICY_SCRIPT_NAME = f"{INTEGRATION_NAME} - UnblockIpsInPolicy"
UNBLOCK_URLS_SCRIPT_NAME = f"{INTEGRATION_NAME} - UnblockURLs"

ITEMS_PER_REQUEST = 50
