[project]
name = "mp"
version = "0.3.2"
description = "General Purpose CLI tool for Google SecOps Marketplace"
readme = "README.md"
authors = [
    { name = "Tal Shapir", email = "talshapir@google.com" },
    { name = "Iddo Arie", email = "iddoa@google.com" },
]
requires-python = ">=3.11"
keywords = [
    "mp",
    "google",
    "secops",
    "soar",
    "marketplace"
]

classifiers = [
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3 :: Only",
]
dependencies = [
    "libcst>=1.8.0",
    "mypy>=1.16.0",
    "pip>=25.1.1",
    "pydantic>=2.11.5",
    "pyyaml>=6.0.2",
    "rich>=14.0.0",
    "ruff>=0.11.13",
    "toml>=0.10.2",
    "typer>=0.16.0",
    "uv>=0.7.12",
]

[dependency-groups]
dev = [
    "pytest>=8.4.0",
    "pytest-cov>=6.1.1",
    "pytest-xdist>=3.7.0",
    "types-pyyaml>=6.0.12.20250516",
    "types-toml>=0.10.8.20240310",
]

[project.scripts]
mp = "mp:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.urls]
Repository = "https://github.com/chronicle/marketplace/tree/main/packages/mp"

[tool.mypy]
plugins = ['pydantic.mypy']
exclude = [
    '\.?venv',
    'build',
    'dist',
]

[tool.pytest.ini_options]
pythonpath = "src"
addopts = [
    "--import-mode=importlib",
]
testpaths = [
    "tests/",
]
