name: Build Marketpalce

on:
  push:
    branches:
      - '**'
    paths:
      - '**/integrations/commercial/**'
      - '**/integrations/third_party/**'
  pull_request:
    branches:
      - '**'
    paths:
      - '**/integrations/commercial/**'
      - '**/integrations/third_party/**'

jobs:
  mp_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install mp package
      run: |
        pip install --upgrade pip
        pip install -e ./packages/mp

    - name: Run mp check with changed files
      shell: bash
      run: |
        mp config --marketplace-path . --processes 10 --display-config
        mp build --repository third_party --repository commercial
