# .github/workflows/commenter.yml
name: Comment on Validation Failure

# This workflow is triggered by the completion of another workflow.
on:
  workflow_run:
    # The name of the workflow that must complete before this one runs.
    workflows: ["Validate marketplace integrations"]
    types:
    - completed

# These permissions are granted because this workflow runs in the context
# of the base repository, not the fork.
permissions:
  pull-requests: write

jobs:
  comment_on_pr:
    runs-on: ubuntu-latest
    
    # We only want to run this job if:
    # 1. The triggering workflow failed.
    # 2. The triggering event was a pull request.
    if: github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.event == 'pull_request'

    steps:
    - name: Download validation report artifact
      uses: actions/download-artifact@v4
      with:
        name: validation-report-md
        # The artifact is downloaded from the triggering workflow run
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ github.event.workflow_run.id }}

    - name: Comment on PR with Collapsible Report
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const reportPath = './validation_report.md'; // Path where download-artifact places the file
          const reportBody = fs.readFileSync(reportPath, 'utf8');

          const finalComment = `❌ **Marketplace Validation Failed**
          <details>
          <summary>Click to view the full validation report</summary>
          ---
          ${reportBody}
          </details>`;

          // Get the PR number from the 'workflow_run' event payload
          const prNumber = github.event.workflow_run.pull_requests[0].number;

          github.rest.issues.createComment({
            issue_number: prNumber,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: finalComment
          });