name: Require Checklist
permissions:
  contents: read
on:
  pull_request:
    types: [ opened, edited, synchronize ]
  issues:
    types: [ opened, edited, deleted ]

jobs:
  require_checklist:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/require-checklist-action@v2
        with:
          requireChecklist: false
