name: Test integrations
permissions:
  contents: read
  issues: write

on:
  push:
    branches:
    - '**'
  pull_request_target:
    types: [opened, synchronize]

jobs:
  test_integrations:
    runs-on: ubuntu-latest

    steps:
    # Conditional checkout for pull_request_target events
    # This ensures we checkout the specific PR head for security and correctness
    # when the workflow is triggered by a pull request from a fork.
    - name: Checkout PR head (for pull_request_target)
      if: github.event_name == 'pull_request_target'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    # Conditional checkout for push events
    # This ensures the workflow checks out the current branch for direct pushes.
    - name: Checkout current branch (for push)
      if: github.event_name == 'push'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        # For push events, 'github.ref' refers to the branch or tag that triggered the workflow.
        # This ensures the correct code is checked out for direct pushes.
        ref: ${{ github.ref }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install mp package
      run: |
        pip install --upgrade pip
        pip install -e ./packages/mp

    - name: Run integration tests
      id: test
      continue-on-error: true
      shell: bash
      env:
        # Pass the PR head SHA as an environment variable to the Python script
        # ONLY if the event is pull_request_target.
        # This is needed because GITHUB_SHA points to the base branch for pull_request_target.
        PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      run: |
        # Your Python script will need to read PR_HEAD_SHA instead of GITHUB_SHA
        # when running in the context of a pull_request_target event.
        mp config --marketplace-path . --processes 10 --display-config
        mp test --repository third_party --repository commercial --raise-error-on-violations

    - name: Comment on PR with Collapsible Report
      # This step will now succeed because the workflow has 'issues: write' permission.
      # The condition ensures it only runs for pull_request_target events and if tests failed.
      if: steps.test.outcome == 'failure'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const reportPath = './artifacts/test_report.md';
          const reportBody = fs.readFileSync(reportPath, 'utf8');

          const finalComment = `❌ **Integration Tests Failed**
          <details>
          <summary>Click to view the full test report</summary>
          ---
          ${reportBody}
          </details>`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: finalComment
          });

    - name: Fail the workflow if tests failed
      # This step runs for both push and pull_request_target if tests failed.
      if: steps.test.outcome == 'failure'
      run: |
        echo "Integration test step failed. Failing the workflow."
        exit 1

    - name: Upload Markdown Report Artifact
      # This step runs regardless of success or failure.
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-report-md
        path: ./artifacts/test_report.md
        retention-days: 2
