name: Comment on Test Failure

on:
  workflow_run:
    workflows: ["Test Integrations"]
    types:
    - completed

permissions:
  pull-requests: write

jobs:
  post_comment:
    runs-on: ubuntu-latest

    if: github.event.workflow_run.conclusion == 'failure'

    steps:
    - name: Download test report
      uses: actions/download-artifact@v4
      with:
        name: test-report-md
        run-id: ${{ github.event.workflow_run.id }}

    - name: Comment on PR with Collapsible Report
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');

          const pr = github.event.workflow_run.pull_requests[0];
          
          if (!pr) {
            console.log('Could not find the pull request associated with this workflow run.');
            return;
          }
          
          const reportPath = './artifacts/test_report.md';
          
          if (!fs.existsSync(reportPath)) {
            console.log(`Test report file not found at path: ${reportPath}`);
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: '❌ **Integration Tests Failed**\n\nThe test report artifact could not be found.'
            });
            return;
          }
          
          const reportBody = fs.readFileSync(reportPath, 'utf8');
          
          const finalComment = `❌ **Integration Tests Failed**
          <details>
          <summary>Click to view the full test report</summary>
          
          ---
          
          ${reportBody}
          
          </details>`;
          
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: pr.number,
            body: finalComment
          });