name: Test integrations

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
    - '**'
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
    - '**'

jobs:
  test_integrations:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository at PR head
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install mp package
      run: |
        pip install --upgrade pip
        pip install -e ./packages/mp

    - name: Run integration tests
      id: test
      continue-on-error: true
      shell: bash
      run: |
        mp config --marketplace-path . --processes 10 --display-config
        mp test --repository third_party --repository commercial --raise-error-on-violations

    - name: Comment on PR with Collapsible Report
      if: github.event_name == 'pull_request_target' && steps.test.outcome == 'failure'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const reportPath = './artifacts/test_report.md';
          let reportBody = 'Test report not found.'; // Default message

          // Check if the report file exists before reading
          if (fs.existsSync(reportPath)) {
            reportBody = fs.readFileSync(reportPath, 'utf8');
          }

          const finalComment = `❌ **Integration Tests Failed**
          <details>
          <summary>Click to view the full test report</summary>
          
          ---
          
          ${reportBody}
          
          </details>`;
          
          // This API call will now succeed for PRs from forks.
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: finalComment
          });

    - name: Fail the workflow if tests failed
      if: steps.test.outcome == 'failure'
      run: |
        echo "Integration test step failed. Failing the workflow."
        exit 1

    - name: Upload Markdown Report Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-report-md
        path: ./artifacts/test_report.md
        retention-days: 2