name: Uv Lock Validation
on:
  pull_request:
    branches:
    - uv-check
  push:
    branches:
    - uv-check
  schedule:
  - cron: '0 0 * * *'

jobs:
  validate_uv_lock_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0


    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: 'latest'
        python-version: '3.11'

    - name: Validate uv.lock files
      run: |
        failed_dirs=()
        while IFS= read -r -d $'\0' lockfile; do
          dir=$(dirname "$lockfile")
          if [ -f "$dir/pyproject.toml" ]; then
            echo "Validating lock file in $dir"
            if ! (cd "$dir" && uv lock --check); then
              echo "ERROR: Validation failed for $dir"
              failed_dirs+=("$dir")
            fi
          fi
        done < <(find integrations -name uv.lock -print0)

        if [ ${#failed_dirs[@]} -ne 0 ]; then
          echo ""
          echo "Lock file validation failed for the following integrations:"
          for dir in "${failed_dirs[@]}"; do
            echo "- $dir"
          done
          exit 1
        fi

        echo "All lock files are consistent."