name: Validate marketplace integrations
permissions:
  contents: read
  pull-requests: write
on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'

jobs:
  mp_validates:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install mp package
      run: |
        pip install --upgrade pip
        pip install -e ./packages/mp

    - name: Validates all integrations
      id: validate_output
      shell: bash
      run: |
        mp config --marketplace-path . --processes 10 --display-config
        # Run the validation, capture output, and exit code
        # Use || true to prevent the step from failing the job immediately
        # You can also just redirect output and let the continue-on-error handle it.
        mp validate --repository third_party --only-pre-build > validation_output.txt 2>&1
        echo "validation_output=$(cat validation_output.txt)" >> "$GITHUB_OUTPUT"
      continue-on-error: true # <--- Add this line here

    # New step to find the associated PR number for push events
    - name: Find Pull Request for Push
      id: find_pr
      if: github.event_name == 'push'
      uses: jwalton/gh-find-current-pr@v1
      with:
        state: open

    - name: Add PR comment
      # Condition to run for pull_request events OR for push events where a PR was found
      if: |
        github.event_name == 'pull_request' ||
        (github.event_name == 'push' && steps.find_pr.outputs.number)
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.pull_request.number || steps.find_pr.outputs.number }}
        body: |
          ### Marketplace Integration Validation Report

          ```
          ${{ steps.validate_output.outputs.validation_output }}
          ```

          [View Full Validation Report](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

    - name: Upload Report Artifact
      # This already has if: always(), so it will run even if previous steps failed
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: validation-report
        path: ./artifacts/validation-report.html
        retention-days: 2