name: Validate marketplace integrations
permissions:
  contents: read
  pull-requests: write # Add permission to write to pull requests
on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'

jobs:
  mp_validates:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install mp package
      run: |
        pip install --upgrade pip
        # This installs your local 'mp' tool so it can be used in the command line
        pip install -e ./packages/mp

    - name: Validates all integrations
      id: validate_output # Add an ID to this step
      shell: bash
      run: |
        mp config --marketplace-path . --processes 10 --display-config
        mp validate --repository third_party --only-pre-build > validation_output.txt 2>&1
        echo "validation_output=$(cat validation_output.txt)" >> "$GITHUB_OUTPUT"

    # New step to find the associated PR number for push events
    - name: Find Pull Request for Push
      id: find_pr
      # Only run this step if the event is a 'push'
      if: github.event_name == 'push'
      uses: jwalton/gh-find-current-pr@v1
      with:
        state: open # Only find open PRs
        # The action automatically uses the current commit SHA from the push event

    - name: Add PR comment
      # Condition now checks for pull_request event OR if a PR was found for a push event
      if: |
        github.event_name == 'pull_request' ||
        (github.event_name == 'push' && steps.find_pr.outputs.number)
      uses: peter-evans/create-or-update-comment@v3
      with:
        # Use the PR number from the pull_request event OR from the find_pr action
        issue-number: ${{ github.event.pull_request.number || steps.find_pr.outputs.number }}
        body: |
          ### Marketplace Integration Validation Report

          ```
          ${{ steps.validate_output.outputs.validation_output }}
          ```

          [View Full Validation Report](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

    - name: Upload Report Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: validation-report
        path: ./artifacts/validation-report.html
        retention-days: 2