name: Post Validation Report

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to comment on'
        required: true
      artifact_name:
        description: 'Artifact name (default: validation-report-md)'
        default: 'validation-report-md'
        required: true

permissions:
  contents: read
  pull-requests: write

jobs:
  post-comment:
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ github.event.inputs.artifact_name }}
        path: ./artifact

    - name: Post PR comment
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          const reportPath = path.join('./artifact', 'validation_report.md');
          
          if (!fs.existsSync(reportPath)) {
            throw new Error('Validation report not found at expected location.');
          }
          
          const reportBody = fs.readFileSync(reportPath, 'utf8');
          
          const finalComment = `❌ **Marketplace Validation Failed**
            <details>
            <summary>Click to view the full validation report</summary>
          
          ---
            
            ${reportBody}
            
            </details>`;
            
            await github.rest.issues.createComment({
          issue_number: Number('${{ github.event.inputs.pr_number }}'),
          owner: context.repo.owner,
          repo: context.repo.repo,
          body: finalComment
          });
