name: Validate marketplace integrations

on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'

jobs:
  mp-validates:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install mp package
      run: |
        pip install --upgrade pip
        pip install -e ./packages/mp

    - name: Run Validations
      id: validate
      continue-on-error: true
      shell: bash
      run: |
        mp config --marketplace-path . --processes 10 --display-config
        mp validate --repository third_party --only-pre-build

    - name: Upload Markdown Report Artifact
      if: steps.validate.outcome == 'failure'
      uses: actions/upload-artifact@v4
      with:
        name: validation-report-md
        path: ./artifacts/validation_report.md
        retention-days: 2

    - name: Fail the workflow if validation failed
      if: steps.validate.outcome == 'failure'
      run: |
        echo "Validation step failed. Failing the workflow."
        exit 1
