name: Validate marketplace integrations

on:
  pull_request:

permissions:
  contents: read

jobs:
  mp_validates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python...
      - name: Install mp package...
      - name: Run Validations
        id: validate
        continue-on-error: true
        run: mp validate --repository third_party --only-pre-build

      - name: Upload validation report
        # Always run this, but it will only upload if the file exists
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: validation-report
          path: ./artifacts/validation_report.md
          retention-days: 1
