name: Comment on PR with Validation Report

permissions:
  contents: read
  pull-requests: write

on:
  workflow_run:
    workflows: ["Validate marketplace integrations"]
    types:
    - completed

jobs:
  comment:
    if: github.event.workflow_run.conclusion == 'failure'
    runs-on: ubuntu-latest

    steps:
    - name: Download validation report
      uses: actions/download-artifact@v4
      with:
        name: validation-report-md
        run-id: ${{ github.event.workflow_run.id }}

    - name: Comment on PR
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const reportBody = fs.readFileSync('./validation_report.md', 'utf8');
          
          const finalComment = `❌ **Marketplace Validation Failed**
          <details>
          <summary>Click to view the full validation report</summary>
          ---
          ${reportBody}
          </details>`;
          
          const prNumber = github.event.workflow_run.pull_requests[0].number;
          
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
            body: finalComment
          });
