name: Validate marketplace integrations

# Define permissions for the GITHUB_TOKEN.
# 'contents: read' is needed for actions/checkout to clone the repository.
# 'issues: write' is the minimal permission required to add comments to PRs or Issues.
# This is more restrictive and secure than 'pull-requests: write', as it prevents
# the workflow from performing actions like merging pull requests.
permissions:
  contents: read
  issues: write

on:
  push:
    branches:
    - '**'
  pull_request_target:
    types: [opened, synchronize]

jobs:
  mp-validates:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout PR head (for pull_request_target)
      if: github.event_name == 'pull_request_target'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Checkout current branch (for push)
      if: github.event_name == 'push'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.ref }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install mp package
      run: |
        pip install --upgrade pip
        pip install -e ./packages/mp

    - name: Print GitHub Event Context
      run: echo "${{ toJSON(github.event) }}"

    - name: Run Validations
      id: validate
      continue-on-error: true
      shell: bash
      env:
        PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      run: |
        mp config --marketplace-path . --processes 10 --display-config
        mp validate --repository third_party --only-pre-build

    - name: Upload Markdown Report Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: validation-report-md
        path: ./artifacts/validation_report.md
        retention-days: 2

    - name: Comment on PR with Collapsible Report
      if: github.event_name == 'pull_request_target' && steps.validate.outcome == 'failure'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const reportPath = './artifacts/validation_report.md';
          const reportBody = fs.readFileSync(reportPath, 'utf8');

          const finalComment = `❌ **Marketplace Validation Failed**
          <details>
          <summary>Click to view the full validation report</summary>
          ---
          ${reportBody}
          </details>`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: finalComment
          });

    - name: Fail the workflow if validation failed
      if: steps.validate.outcome == 'failure'
      run: |
        echo "Validation step failed. Failing the workflow."
        exit 1