name: Validate marketplace integrations

# Required permissions:
# contents: read - to checkout the repository
# pull-requests: write - to post a comment on the pull request
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'

jobs:
  mp_validates:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install mp package
      run: |
        pip install --upgrade pip
        pip install -e ./packages/mp

    - name: Run Validations
      # This step runs the validation command. Its live output will appear in the terminal.
      # The Python script itself will generate the report.md file inside the ./artifacts directory.
      # 'continue-on-error: true' allows the workflow to proceed to the commenting step even if this fails.
      id: validate
      continue-on-error: true
      shell: bash
      run: |
        mp config --marketplace-path . --processes 10 --display-config
        mp validate --repository third_party --only-pre-build

    - name: Comment on PR with Markdown Report
      # This step only runs if:
      # 1. The trigger is a pull request.
      # 2. The previous 'validate' step failed.
      if: github.event_name == 'pull_request' && steps.validate.outcome == 'failure'
      uses: actions/github-script@v7
      with:
        script: |
          // Use the 'fs' module to read the .md report file created by the validation script.
          const fs = require('fs');
          const reportPath = './artifacts/report.md';
          const reportBody = fs.readFileSync(reportPath, 'utf8');

          // Format the comment. Since the report is already in Markdown, we can embed it directly.
          const finalComment = `❌ **Marketplace Validation Failed**

          A validation report has been generated:
          
          ---
          ${reportBody}`;
          
          // Post the comment to the pull request.
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: finalComment
          });

    - name: Fail the workflow if validation failed
      # This step ensures the entire job is marked as a failure if the validation step failed.
      if: steps.validate.outcome == 'failure'
      run: |
        echo "Validation step failed. Failing the workflow."
        exit 1

    - name: Upload Markdown Report Artifact
      # Uploads the generated Markdown report.
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: validation-report-md
        path: ./artifacts/report.md
        retention-days: 2

    - name: Upload HTML Report Artifact
      # Uploads the original HTML report.
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: validation-report-html
        path: ./artifacts/validation-report.html
        retention-days: 2